### ISSUE TITLE
JQ.Path returns the wrong value in LinqPad

### ISSUE THREAD

**Issue by Arithmomaniac** [devlooped/jq#17]
## Describe the Bug

JQ.Path incorrectly assumes the jq.exe assembly will always be in `AppContext.BaseDirectory`, when that is not the case. This causes `FileNotFoundException`s at runtime.

## Steps to Reproduce

Using LinqPad 8:

```c#
JQ.Path.Dump();
typeof(JQ).Assembly.Location.Dump();

try { var _ = (await JQ.ExecuteAsync("""{"records":[]}""", """.records[]""")); }
catch (Exception ex) { ex.ToString().Dump(); }
```

## Expected Behavior

The path points to the actual location on disk (`C:\Users\arithmomaniac\.nuget\packages\devlooped.jq\1.7.1.1\tools\jq-windows-amd64.exe`)

## Exception with Stack Trace

Console output:

```text
C:\Users\arithmomaniac\AppData\Local\Temp\LINQPad8\_pkwjxppc\shadow-3\lib\jq-windows-amd64.exe
C:\Users\arithmomaniac\.nuget\packages\Devlooped.JQ\1.7.1.1\lib\net8.0\JQ.dll
```

```text
System.IO.FileNotFoundException: JQ executable not found.
File name: 'C:\Users\arithmomaniac\AppData\Local\Temp\LINQPad8\_pkwjxppc\shadow-3\lib\jq-windows-amd64.exe'
   at Devlooped.JQ.ExecuteAsync(String json, String query) in /_/src/JQ/JQ.cs:line 60
   at UserQuery.Main() in C:\Users\arithmomaniac\AppData\Local\Temp\LINQPad8\_pkwjxppc\vrmzoe\LINQPadQuery:line 4
```

## Version Info

dotnet 8
Devlooped.JQ 1.7.1.1

## Additional Info

Seems like the right way to "include" the executable may be more like this: https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Thank you for reporting the issue. Since my initial usage of this tool is within the context of a dotnet global tool (and since the included executable is provided as a runtime asset), I did not consider this "library-only" usage. 

I'll look into it.

**Comment by Arithmomaniac** [comment]
Instead of gifting you a license (not that you don't deserve it 😉), you  can see a similar result in [NetPad](https://github.com/tareqimbasher/NetPad), a free clone:

```
C:\Users\avilevin\AppData\Local\Temp\NetPad\Processes\0fdf6648-fd68-468f-88f5-c149a180c0f2\lib\jq-windows-amd64.exe
C:\Users\avilevin\AppData\Local\Temp\NetPad\Processes\0fdf6648-fd68-468f-88f5-c149a180c0f2\JQ.dll
System.IO.FileNotFoundException: JQ executable not found.
File name: 'C:\Users\avilevin\AppData\Local\Temp\NetPad\Processes\0fdf6648-fd68-468f-88f5-c149a180c0f2\lib\jq-windows-amd64.exe'
   at Devlooped.JQ.ExecuteAsync(String json, String query) in /_/src/JQ/JQ.cs:line 60
   at Program.<Main>$(String[] args) in :line 26
```

(Here `JQ.dll` isn't even pointing to the package directory; that might be a bug in NetPad itself. If you try the `GeneratePathProperty` guidance and it still doesn't work, I'll file the bug with them.)

**Comment by kzu** [comment]
Hi @Arithmomaniac. I'll consider a PR for this. For the primary usage in multiple core scenarios (console apps, web apps, azure functions), the current approach is working great for me, so this is very low priority ATM.

**Comment by kzu** [comment]
You can now back a specific issue to help prioritizing: [back an issue](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped) 🙏
